/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ConfigResponse {
    'EXCLUDED_PLATFORMS': Array<string>;
    'EXCLUDED_SINGLE_EXT': Array<string>;
    'EXCLUDED_SINGLE_FILES': Array<string>;
    'EXCLUDED_MULTI_FILES': Array<string>;
    'EXCLUDED_MULTI_PARTS_EXT': Array<string>;
    'EXCLUDED_MULTI_PARTS_FILES': Array<string>;
    'PLATFORMS_BINDING': { [key: string]: string; };
    'PLATFORMS_VERSIONS': { [key: string]: string; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "EXCLUDED_PLATFORMS",
            "baseName": "EXCLUDED_PLATFORMS",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "EXCLUDED_SINGLE_EXT",
            "baseName": "EXCLUDED_SINGLE_EXT",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "EXCLUDED_SINGLE_FILES",
            "baseName": "EXCLUDED_SINGLE_FILES",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "EXCLUDED_MULTI_FILES",
            "baseName": "EXCLUDED_MULTI_FILES",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "EXCLUDED_MULTI_PARTS_EXT",
            "baseName": "EXCLUDED_MULTI_PARTS_EXT",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "EXCLUDED_MULTI_PARTS_FILES",
            "baseName": "EXCLUDED_MULTI_PARTS_FILES",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "PLATFORMS_BINDING",
            "baseName": "PLATFORMS_BINDING",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "PLATFORMS_VERSIONS",
            "baseName": "PLATFORMS_VERSIONS",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConfigResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
