/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SimpleRomSchema } from '../models/SimpleRomSchema.js';
import { HttpFile } from '../http/http.js';

export class CustomLimitOffsetPageSimpleRomSchema {
    'items': Array<SimpleRomSchema>;
    'total': number | null;
    'limit': number | null;
    'offset': number | null;
    'charIndex': { [key: string]: number; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<SimpleRomSchema>",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": ""
        },
        {
            "name": "charIndex",
            "baseName": "char_index",
            "type": "{ [key: string]: number; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomLimitOffsetPageSimpleRomSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
