/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CollectionSchema } from '../models/CollectionSchema';
import { RomFileSchema } from '../models/RomFileSchema';
import { RomIGDBMetadata } from '../models/RomIGDBMetadata';
import { RomMetadataSchema } from '../models/RomMetadataSchema';
import { RomMobyMetadata } from '../models/RomMobyMetadata';
import { RomRAMetadata } from '../models/RomRAMetadata';
import { RomSSMetadata } from '../models/RomSSMetadata';
import { RomUserSchema } from '../models/RomUserSchema';
import { SaveSchema } from '../models/SaveSchema';
import { ScreenshotSchema } from '../models/ScreenshotSchema';
import { SiblingRomSchema } from '../models/SiblingRomSchema';
import { StateSchema } from '../models/StateSchema';
import { UserNotesSchema } from '../models/UserNotesSchema';
import { HttpFile } from '../http/http';

export class DetailedRomSchema {
    'id': number;
    'igdbId': number | null;
    'sgdbId': number | null;
    'mobyId': number | null;
    'ssId': number | null;
    'raId': number | null;
    'platformId': number;
    'platformSlug': string;
    'platformFsSlug': string;
    'platformName': string;
    'platformCustomName': string | null;
    'platformDisplayName': string;
    'fsName': string;
    'fsNameNoTags': string;
    'fsNameNoExt': string;
    'fsExtension': string;
    'fsPath': string;
    'fsSizeBytes': number;
    'name': string | null;
    'slug': string | null;
    'summary': string | null;
    'alternativeNames': Array<string>;
    'youtubeVideoId': string | null;
    'metadatum': RomMetadataSchema;
    'igdbMetadata': RomIGDBMetadata | null;
    'mobyMetadata': RomMobyMetadata | null;
    'ssMetadata': RomSSMetadata | null;
    'pathCoverSmall': string | null;
    'pathCoverLarge': string | null;
    'urlCover': string | null;
    'hasManual': boolean;
    'pathManual': string | null;
    'urlManual': string | null;
    'isUnidentified': boolean;
    'revision': string | null;
    'regions': Array<string>;
    'languages': Array<string>;
    'tags': Array<string>;
    'crcHash': string | null;
    'md5Hash': string | null;
    'sha1Hash': string | null;
    'multi': boolean;
    'files': Array<RomFileSchema>;
    'fullPath': string;
    'createdAt': Date;
    'updatedAt': Date;
    'mergedRaMetadata': RomRAMetadata | null;
    'mergedScreenshots': Array<string>;
    'siblings': Array<SiblingRomSchema>;
    'romUser': RomUserSchema;
    'userSaves': Array<SaveSchema>;
    'userStates': Array<StateSchema>;
    'userScreenshots': Array<ScreenshotSchema>;
    'userNotes': Array<UserNotesSchema>;
    'userCollections': Array<CollectionSchema>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "igdbId",
            "baseName": "igdb_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "sgdbId",
            "baseName": "sgdb_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "mobyId",
            "baseName": "moby_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "ssId",
            "baseName": "ss_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "raId",
            "baseName": "ra_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "platformId",
            "baseName": "platform_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "platformSlug",
            "baseName": "platform_slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "platformFsSlug",
            "baseName": "platform_fs_slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "platformName",
            "baseName": "platform_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "platformCustomName",
            "baseName": "platform_custom_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "platformDisplayName",
            "baseName": "platform_display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "fsName",
            "baseName": "fs_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "fsNameNoTags",
            "baseName": "fs_name_no_tags",
            "type": "string",
            "format": ""
        },
        {
            "name": "fsNameNoExt",
            "baseName": "fs_name_no_ext",
            "type": "string",
            "format": ""
        },
        {
            "name": "fsExtension",
            "baseName": "fs_extension",
            "type": "string",
            "format": ""
        },
        {
            "name": "fsPath",
            "baseName": "fs_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "fsSizeBytes",
            "baseName": "fs_size_bytes",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "alternativeNames",
            "baseName": "alternative_names",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "youtubeVideoId",
            "baseName": "youtube_video_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadatum",
            "baseName": "metadatum",
            "type": "RomMetadataSchema",
            "format": ""
        },
        {
            "name": "igdbMetadata",
            "baseName": "igdb_metadata",
            "type": "RomIGDBMetadata",
            "format": ""
        },
        {
            "name": "mobyMetadata",
            "baseName": "moby_metadata",
            "type": "RomMobyMetadata",
            "format": ""
        },
        {
            "name": "ssMetadata",
            "baseName": "ss_metadata",
            "type": "RomSSMetadata",
            "format": ""
        },
        {
            "name": "pathCoverSmall",
            "baseName": "path_cover_small",
            "type": "string",
            "format": ""
        },
        {
            "name": "pathCoverLarge",
            "baseName": "path_cover_large",
            "type": "string",
            "format": ""
        },
        {
            "name": "urlCover",
            "baseName": "url_cover",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasManual",
            "baseName": "has_manual",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "pathManual",
            "baseName": "path_manual",
            "type": "string",
            "format": ""
        },
        {
            "name": "urlManual",
            "baseName": "url_manual",
            "type": "string",
            "format": ""
        },
        {
            "name": "isUnidentified",
            "baseName": "is_unidentified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "revision",
            "baseName": "revision",
            "type": "string",
            "format": ""
        },
        {
            "name": "regions",
            "baseName": "regions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "languages",
            "baseName": "languages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "crcHash",
            "baseName": "crc_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "md5Hash",
            "baseName": "md5_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha1Hash",
            "baseName": "sha1_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "multi",
            "baseName": "multi",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<RomFileSchema>",
            "format": ""
        },
        {
            "name": "fullPath",
            "baseName": "full_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "mergedRaMetadata",
            "baseName": "merged_ra_metadata",
            "type": "RomRAMetadata",
            "format": ""
        },
        {
            "name": "mergedScreenshots",
            "baseName": "merged_screenshots",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "siblings",
            "baseName": "siblings",
            "type": "Array<SiblingRomSchema>",
            "format": ""
        },
        {
            "name": "romUser",
            "baseName": "rom_user",
            "type": "RomUserSchema",
            "format": ""
        },
        {
            "name": "userSaves",
            "baseName": "user_saves",
            "type": "Array<SaveSchema>",
            "format": ""
        },
        {
            "name": "userStates",
            "baseName": "user_states",
            "type": "Array<StateSchema>",
            "format": ""
        },
        {
            "name": "userScreenshots",
            "baseName": "user_screenshots",
            "type": "Array<ScreenshotSchema>",
            "format": ""
        },
        {
            "name": "userNotes",
            "baseName": "user_notes",
            "type": "Array<UserNotesSchema>",
            "format": ""
        },
        {
            "name": "userCollections",
            "baseName": "user_collections",
            "type": "Array<CollectionSchema>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DetailedRomSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
