/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EmulationDict {
    'DISABLE_EMULATOR_JS': boolean;
    'DISABLE_RUFFLE_RS': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "DISABLE_EMULATOR_JS",
            "baseName": "DISABLE_EMULATOR_JS",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "DISABLE_RUFFLE_RS",
            "baseName": "DISABLE_RUFFLE_RS",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EmulationDict.attributeTypeMap;
    }

    public constructor() {
    }
}
