/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FirmwareSchema {
    'id': number;
    'fileName': string;
    'fileNameNoTags': string;
    'fileNameNoExt': string;
    'fileExtension': string;
    'filePath': string;
    'fileSizeBytes': number;
    'fullPath': string;
    'isVerified': boolean;
    'crcHash': string;
    'md5Hash': string;
    'sha1Hash': string;
    'createdAt': Date;
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "fileName",
            "baseName": "file_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileNameNoTags",
            "baseName": "file_name_no_tags",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileNameNoExt",
            "baseName": "file_name_no_ext",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileExtension",
            "baseName": "file_extension",
            "type": "string",
            "format": ""
        },
        {
            "name": "filePath",
            "baseName": "file_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileSizeBytes",
            "baseName": "file_size_bytes",
            "type": "number",
            "format": ""
        },
        {
            "name": "fullPath",
            "baseName": "full_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "isVerified",
            "baseName": "is_verified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "crcHash",
            "baseName": "crc_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "md5Hash",
            "baseName": "md5_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha1Hash",
            "baseName": "sha1_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return FirmwareSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
