/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class FrontendDict {
    'UPLOAD_TIMEOUT': number;
    'DISABLE_USERPASS_LOGIN': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "UPLOAD_TIMEOUT",
            "baseName": "UPLOAD_TIMEOUT",
            "type": "number",
            "format": ""
        },
        {
            "name": "DISABLE_USERPASS_LOGIN",
            "baseName": "DISABLE_USERPASS_LOGIN",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FrontendDict.attributeTypeMap;
    }

    public constructor() {
    }
}
