/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EmulationDict } from '../models/EmulationDict';
import { FilesystemDict } from '../models/FilesystemDict';
import { FrontendDict } from '../models/FrontendDict';
import { MetadataSourcesDict } from '../models/MetadataSourcesDict';
import { OIDCDict } from '../models/OIDCDict';
import { SchedulerDict } from '../models/SchedulerDict';
import { SystemDict } from '../models/SystemDict';
import { WatcherDict } from '../models/WatcherDict';
import { HttpFile } from '../http/http';

export class HeartbeatResponse {
    'SYSTEM': SystemDict;
    'WATCHER': WatcherDict;
    'SCHEDULER': SchedulerDict;
    'METADATA_SOURCES': MetadataSourcesDict;
    'FILESYSTEM': FilesystemDict;
    'EMULATION': EmulationDict;
    'FRONTEND': FrontendDict;
    'OIDC': OIDCDict;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "SYSTEM",
            "baseName": "SYSTEM",
            "type": "SystemDict",
            "format": ""
        },
        {
            "name": "WATCHER",
            "baseName": "WATCHER",
            "type": "WatcherDict",
            "format": ""
        },
        {
            "name": "SCHEDULER",
            "baseName": "SCHEDULER",
            "type": "SchedulerDict",
            "format": ""
        },
        {
            "name": "METADATA_SOURCES",
            "baseName": "METADATA_SOURCES",
            "type": "MetadataSourcesDict",
            "format": ""
        },
        {
            "name": "FILESYSTEM",
            "baseName": "FILESYSTEM",
            "type": "FilesystemDict",
            "format": ""
        },
        {
            "name": "EMULATION",
            "baseName": "EMULATION",
            "type": "EmulationDict",
            "format": ""
        },
        {
            "name": "FRONTEND",
            "baseName": "FRONTEND",
            "type": "FrontendDict",
            "format": ""
        },
        {
            "name": "OIDC",
            "baseName": "OIDC",
            "type": "OIDCDict",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HeartbeatResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
