/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class MetadataSourcesDict {
    'ANY_SOURCE_ENABLED': boolean;
    'IGDB_API_ENABLED': boolean;
    'MOBY_API_ENABLED': boolean;
    'SS_API_ENABLED': boolean;
    'STEAMGRIDDB_API_ENABLED': boolean;
    'RA_API_ENABLED': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ANY_SOURCE_ENABLED",
            "baseName": "ANY_SOURCE_ENABLED",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "IGDB_API_ENABLED",
            "baseName": "IGDB_API_ENABLED",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "MOBY_API_ENABLED",
            "baseName": "MOBY_API_ENABLED",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "SS_API_ENABLED",
            "baseName": "SS_API_ENABLED",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "STEAMGRIDDB_API_ENABLED",
            "baseName": "STEAMGRIDDB_API_ENABLED",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "RA_API_ENABLED",
            "baseName": "RA_API_ENABLED",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetadataSourcesDict.attributeTypeMap;
    }

    public constructor() {
    }
}
