/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FirmwareSchema } from '../models/FirmwareSchema';
import { HttpFile } from '../http/http';

export class PlatformSchema {
    'id': number;
    'slug': string;
    'fsSlug': string;
    'romCount': number;
    'name': string;
    'customName'?: string | null;
    'igdbId'?: number | null;
    'sgdbId'?: number | null;
    'mobyId'?: number | null;
    'ssId'?: number | null;
    'raId'?: number | null;
    'category'?: string | null;
    'generation'?: number | null;
    'familyName'?: string | null;
    'familySlug'?: string | null;
    'url'?: string | null;
    'urlLogo'?: string | null;
    'logoPath'?: string | null;
    'firmware'?: Array<FirmwareSchema>;
    'aspectRatio'?: string;
    'createdAt': Date;
    'updatedAt': Date;
    'fsSizeBytes': number;
    'displayName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "fsSlug",
            "baseName": "fs_slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "romCount",
            "baseName": "rom_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "customName",
            "baseName": "custom_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "igdbId",
            "baseName": "igdb_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "sgdbId",
            "baseName": "sgdb_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "mobyId",
            "baseName": "moby_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "ssId",
            "baseName": "ss_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "raId",
            "baseName": "ra_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string",
            "format": ""
        },
        {
            "name": "generation",
            "baseName": "generation",
            "type": "number",
            "format": ""
        },
        {
            "name": "familyName",
            "baseName": "family_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "familySlug",
            "baseName": "family_slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "urlLogo",
            "baseName": "url_logo",
            "type": "string",
            "format": ""
        },
        {
            "name": "logoPath",
            "baseName": "logo_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "firmware",
            "baseName": "firmware",
            "type": "Array<FirmwareSchema>",
            "format": ""
        },
        {
            "name": "aspectRatio",
            "baseName": "aspect_ratio",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "fsSizeBytes",
            "baseName": "fs_size_bytes",
            "type": "number",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlatformSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
