/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RAGameRomAchievement {
    'raId': number | null;
    'title': string | null;
    'description': string | null;
    'points': number | null;
    'numAwarded': number | null;
    'numAwardedHardcore': number | null;
    'badgeId': string | null;
    'badgeUrlLock': string | null;
    'badgePathLock': string | null;
    'badgeUrl': string | null;
    'badgePath': string | null;
    'displayOrder': number | null;
    'type': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "raId",
            "baseName": "ra_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number",
            "format": ""
        },
        {
            "name": "numAwarded",
            "baseName": "num_awarded",
            "type": "number",
            "format": ""
        },
        {
            "name": "numAwardedHardcore",
            "baseName": "num_awarded_hardcore",
            "type": "number",
            "format": ""
        },
        {
            "name": "badgeId",
            "baseName": "badge_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "badgeUrlLock",
            "baseName": "badge_url_lock",
            "type": "string",
            "format": ""
        },
        {
            "name": "badgePathLock",
            "baseName": "badge_path_lock",
            "type": "string",
            "format": ""
        },
        {
            "name": "badgeUrl",
            "baseName": "badge_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "badgePath",
            "baseName": "badge_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayOrder",
            "baseName": "display_order",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RAGameRomAchievement.attributeTypeMap;
    }

    public constructor() {
    }
}
