/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EarnedAchievement } from '../models/EarnedAchievement';
import { HttpFile } from '../http/http';

export class RAUserGameProgression {
    'romRaId': number | null;
    'maxPossible': number | null;
    'numAwarded': number | null;
    'numAwardedHardcore': number | null;
    'earnedAchievements': Array<EarnedAchievement>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "romRaId",
            "baseName": "rom_ra_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxPossible",
            "baseName": "max_possible",
            "type": "number",
            "format": ""
        },
        {
            "name": "numAwarded",
            "baseName": "num_awarded",
            "type": "number",
            "format": ""
        },
        {
            "name": "numAwardedHardcore",
            "baseName": "num_awarded_hardcore",
            "type": "number",
            "format": ""
        },
        {
            "name": "earnedAchievements",
            "baseName": "earned_achievements",
            "type": "Array<EarnedAchievement>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RAUserGameProgression.attributeTypeMap;
    }

    public constructor() {
    }
}
