/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export enum RomFileCategory {
    Dlc = 'dlc',
    Hack = 'hack',
    Manual = 'manual',
    Patch = 'patch',
    Update = 'update',
    Mod = 'mod',
    Demo = 'demo',
    Translation = 'translation',
    Prototype = 'prototype'
}
