/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IGDBAgeRating } from '../models/IGDBAgeRating';
import { IGDBMetadataPlatform } from '../models/IGDBMetadataPlatform';
import { IGDBRelatedGame } from '../models/IGDBRelatedGame';
import { HttpFile } from '../http/http';

export class RomIGDBMetadata {
    'totalRating'?: string;
    'aggregatedRating'?: string;
    'firstReleaseDate'?: number | null;
    'youtubeVideoId'?: string | null;
    'genres'?: Array<string>;
    'franchises'?: Array<string>;
    'alternativeNames'?: Array<string>;
    'collections'?: Array<string>;
    'companies'?: Array<string>;
    'gameModes'?: Array<string>;
    'ageRatings'?: Array<IGDBAgeRating>;
    'platforms'?: Array<IGDBMetadataPlatform>;
    'expansions'?: Array<IGDBRelatedGame>;
    'dlcs'?: Array<IGDBRelatedGame>;
    'remasters'?: Array<IGDBRelatedGame>;
    'remakes'?: Array<IGDBRelatedGame>;
    'expandedGames'?: Array<IGDBRelatedGame>;
    'ports'?: Array<IGDBRelatedGame>;
    'similarGames'?: Array<IGDBRelatedGame>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "totalRating",
            "baseName": "total_rating",
            "type": "string",
            "format": ""
        },
        {
            "name": "aggregatedRating",
            "baseName": "aggregated_rating",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstReleaseDate",
            "baseName": "first_release_date",
            "type": "number",
            "format": ""
        },
        {
            "name": "youtubeVideoId",
            "baseName": "youtube_video_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "genres",
            "baseName": "genres",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "franchises",
            "baseName": "franchises",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "alternativeNames",
            "baseName": "alternative_names",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "collections",
            "baseName": "collections",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "companies",
            "baseName": "companies",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "gameModes",
            "baseName": "game_modes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "ageRatings",
            "baseName": "age_ratings",
            "type": "Array<IGDBAgeRating>",
            "format": ""
        },
        {
            "name": "platforms",
            "baseName": "platforms",
            "type": "Array<IGDBMetadataPlatform>",
            "format": ""
        },
        {
            "name": "expansions",
            "baseName": "expansions",
            "type": "Array<IGDBRelatedGame>",
            "format": ""
        },
        {
            "name": "dlcs",
            "baseName": "dlcs",
            "type": "Array<IGDBRelatedGame>",
            "format": ""
        },
        {
            "name": "remasters",
            "baseName": "remasters",
            "type": "Array<IGDBRelatedGame>",
            "format": ""
        },
        {
            "name": "remakes",
            "baseName": "remakes",
            "type": "Array<IGDBRelatedGame>",
            "format": ""
        },
        {
            "name": "expandedGames",
            "baseName": "expanded_games",
            "type": "Array<IGDBRelatedGame>",
            "format": ""
        },
        {
            "name": "ports",
            "baseName": "ports",
            "type": "Array<IGDBRelatedGame>",
            "format": ""
        },
        {
            "name": "similarGames",
            "baseName": "similar_games",
            "type": "Array<IGDBRelatedGame>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RomIGDBMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}
