/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class RomMetadataSchema {
    'romId': number;
    'genres': Array<string>;
    'franchises': Array<string>;
    'collections': Array<string>;
    'companies': Array<string>;
    'gameModes': Array<string>;
    'ageRatings': Array<string>;
    'firstReleaseDate': number | null;
    'averageRating': number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "romId",
            "baseName": "rom_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "genres",
            "baseName": "genres",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "franchises",
            "baseName": "franchises",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "collections",
            "baseName": "collections",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "companies",
            "baseName": "companies",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "gameModes",
            "baseName": "game_modes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "ageRatings",
            "baseName": "age_ratings",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "firstReleaseDate",
            "baseName": "first_release_date",
            "type": "number",
            "format": ""
        },
        {
            "name": "averageRating",
            "baseName": "average_rating",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RomMetadataSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
