/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RAGameRomAchievement } from '../models/RAGameRomAchievement';
import { HttpFile } from '../http/http';

export class RomRAMetadata {
    'achievements'?: Array<RAGameRomAchievement>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "achievements",
            "baseName": "achievements",
            "type": "Array<RAGameRomAchievement>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RomRAMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}
