/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RomSSMetadata {
    'ssScore'?: string;
    'firstReleaseDate'?: number | null;
    'alternativeNames'?: Array<string>;
    'companies'?: Array<string>;
    'franchises'?: Array<string>;
    'gameModes'?: Array<string>;
    'genres'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ssScore",
            "baseName": "ss_score",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstReleaseDate",
            "baseName": "first_release_date",
            "type": "number",
            "format": ""
        },
        {
            "name": "alternativeNames",
            "baseName": "alternative_names",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "companies",
            "baseName": "companies",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "franchises",
            "baseName": "franchises",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "gameModes",
            "baseName": "game_modes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "genres",
            "baseName": "genres",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RomSSMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}
