/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export enum RomUserStatus {
    Incomplete = 'incomplete',
    Finished = 'finished',
    Completed100 = 'completed_100',
    Retired = 'retired',
    NeverPlaying = 'never_playing'
}
