/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RomUserStatus } from '../models/RomUserStatus';
import { HttpFile } from '../http/http';

export class RomUserSchema {
    'id': number;
    'userId': number;
    'romId': number;
    'createdAt': Date;
    'updatedAt': Date;
    'lastPlayed': Date | null;
    'noteRawMarkdown': string;
    'noteIsPublic': boolean;
    'isMainSibling': boolean;
    'backlogged': boolean;
    'nowPlaying': boolean;
    'hidden': boolean;
    'rating': number;
    'difficulty': number;
    'completion': number;
    'status': RomUserStatus | null;
    'userUsername': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "romId",
            "baseName": "rom_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastPlayed",
            "baseName": "last_played",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "noteRawMarkdown",
            "baseName": "note_raw_markdown",
            "type": "string",
            "format": ""
        },
        {
            "name": "noteIsPublic",
            "baseName": "note_is_public",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isMainSibling",
            "baseName": "is_main_sibling",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "backlogged",
            "baseName": "backlogged",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "nowPlaying",
            "baseName": "now_playing",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hidden",
            "baseName": "hidden",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rating",
            "baseName": "rating",
            "type": "number",
            "format": ""
        },
        {
            "name": "difficulty",
            "baseName": "difficulty",
            "type": "number",
            "format": ""
        },
        {
            "name": "completion",
            "baseName": "completion",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "RomUserStatus",
            "format": ""
        },
        {
            "name": "userUsername",
            "baseName": "user__username",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RomUserSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


