/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskDict } from '../models/TaskDict';
import { HttpFile } from '../http/http';

export class SchedulerDict {
    'RESCAN': TaskDict;
    'SWITCH_TITLEDB': TaskDict;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "RESCAN",
            "baseName": "RESCAN",
            "type": "TaskDict",
            "format": ""
        },
        {
            "name": "SWITCH_TITLEDB",
            "baseName": "SWITCH_TITLEDB",
            "type": "TaskDict",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SchedulerDict.attributeTypeMap;
    }

    public constructor() {
    }
}
