/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class SearchRomSchema {
    'id'?: number | null;
    'igdbId'?: number | null;
    'mobyId'?: number | null;
    'ssId'?: number | null;
    'slug': string;
    'name': string;
    'summary': string;
    'igdbUrlCover'?: string;
    'mobyUrlCover'?: string;
    'ssUrlCover'?: string;
    'platformId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "igdbId",
            "baseName": "igdb_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "mobyId",
            "baseName": "moby_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "ssId",
            "baseName": "ss_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "igdbUrlCover",
            "baseName": "igdb_url_cover",
            "type": "string",
            "format": ""
        },
        {
            "name": "mobyUrlCover",
            "baseName": "moby_url_cover",
            "type": "string",
            "format": ""
        },
        {
            "name": "ssUrlCover",
            "baseName": "ss_url_cover",
            "type": "string",
            "format": ""
        },
        {
            "name": "platformId",
            "baseName": "platform_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchRomSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
