/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class SiblingRomSchema {
    'id': number;
    'name': string | null;
    'fsNameNoTags': string;
    'fsNameNoExt': string;
    'sortComparator': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "fsNameNoTags",
            "baseName": "fs_name_no_tags",
            "type": "string",
            "format": ""
        },
        {
            "name": "fsNameNoExt",
            "baseName": "fs_name_no_ext",
            "type": "string",
            "format": ""
        },
        {
            "name": "sortComparator",
            "baseName": "sort_comparator",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SiblingRomSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
