/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StatsReturn {
    'PLATFORMS': number;
    'ROMS': number;
    'SAVES': number;
    'STATES': number;
    'SCREENSHOTS': number;
    'TOTAL_FILESIZE_BYTES': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "PLATFORMS",
            "baseName": "PLATFORMS",
            "type": "number",
            "format": ""
        },
        {
            "name": "ROMS",
            "baseName": "ROMS",
            "type": "number",
            "format": ""
        },
        {
            "name": "SAVES",
            "baseName": "SAVES",
            "type": "number",
            "format": ""
        },
        {
            "name": "STATES",
            "baseName": "STATES",
            "type": "number",
            "format": ""
        },
        {
            "name": "SCREENSHOTS",
            "baseName": "SCREENSHOTS",
            "type": "number",
            "format": ""
        },
        {
            "name": "TOTAL_FILESIZE_BYTES",
            "baseName": "TOTAL_FILESIZE_BYTES",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StatsReturn.attributeTypeMap;
    }

    public constructor() {
    }
}
