/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ScreenshotSchema } from '../models/ScreenshotSchema.js';
import { HttpFile } from '../http/http.js';

export class StateSchema {
    'id': number;
    'romId': number;
    'userId': number;
    'fileName': string;
    'fileNameNoTags': string;
    'fileNameNoExt': string;
    'fileExtension': string;
    'filePath': string;
    'fileSizeBytes': number;
    'fullPath': string;
    'downloadPath': string;
    'createdAt': Date;
    'updatedAt': Date;
    'emulator': string | null;
    'screenshot': ScreenshotSchema | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "romId",
            "baseName": "rom_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "fileName",
            "baseName": "file_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileNameNoTags",
            "baseName": "file_name_no_tags",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileNameNoExt",
            "baseName": "file_name_no_ext",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileExtension",
            "baseName": "file_extension",
            "type": "string",
            "format": ""
        },
        {
            "name": "filePath",
            "baseName": "file_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileSizeBytes",
            "baseName": "file_size_bytes",
            "type": "number",
            "format": ""
        },
        {
            "name": "fullPath",
            "baseName": "full_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "downloadPath",
            "baseName": "download_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "emulator",
            "baseName": "emulator",
            "type": "string",
            "format": ""
        },
        {
            "name": "screenshot",
            "baseName": "screenshot",
            "type": "ScreenshotSchema",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StateSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
