/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SystemDict {
    'VERSION': string;
    'SHOW_SETUP_WIZARD': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "VERSION",
            "baseName": "VERSION",
            "type": "string",
            "format": ""
        },
        {
            "name": "SHOW_SETUP_WIZARD",
            "baseName": "SHOW_SETUP_WIZARD",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SystemDict.attributeTypeMap;
    }

    public constructor() {
    }
}
