/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RAProgression } from '../models/RAProgression.js';
import { Role } from '../models/Role.js';
import { HttpFile } from '../http/http.js';

export class UserSchema {
    'id': number;
    'username': string;
    'email': string | null;
    'enabled': boolean;
    'role': Role;
    'oauthScopes': Array<string>;
    'avatarPath': string;
    'lastLogin': Date | null;
    'lastActive': Date | null;
    'raUsername'?: string | null;
    'raProgression'?: RAProgression | null;
    'createdAt': Date;
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "Role",
            "format": ""
        },
        {
            "name": "oauthScopes",
            "baseName": "oauth_scopes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "avatarPath",
            "baseName": "avatar_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastLogin",
            "baseName": "last_login",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastActive",
            "baseName": "last_active",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "raUsername",
            "baseName": "ra_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "raProgression",
            "baseName": "ra_progression",
            "type": "RAProgression",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return UserSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


