/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class VirtualCollectionSchema {
    'name': string;
    'description': string;
    'romIds': Set<number>;
    'romCount': number;
    'pathCoverSmall': string | null;
    'pathCoverLarge': string | null;
    'pathCoversSmall': Array<string>;
    'pathCoversLarge': Array<string>;
    'id': string;
    'type': string;
    'isPublic'?: boolean;
    'isFavorite'?: boolean;
    'isVirtual'?: boolean;
    'createdAt': Date;
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "romIds",
            "baseName": "rom_ids",
            "type": "Set<number>",
            "format": ""
        },
        {
            "name": "romCount",
            "baseName": "rom_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "pathCoverSmall",
            "baseName": "path_cover_small",
            "type": "string",
            "format": ""
        },
        {
            "name": "pathCoverLarge",
            "baseName": "path_cover_large",
            "type": "string",
            "format": ""
        },
        {
            "name": "pathCoversSmall",
            "baseName": "path_covers_small",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "pathCoversLarge",
            "baseName": "path_covers_large",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPublic",
            "baseName": "is_public",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isFavorite",
            "baseName": "is_favorite",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isVirtual",
            "baseName": "is_virtual",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return VirtualCollectionSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
