/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class WatcherDict {
    'ENABLED': boolean;
    'TITLE': string;
    'MESSAGE': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ENABLED",
            "baseName": "ENABLED",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "TITLE",
            "baseName": "TITLE",
            "type": "string",
            "format": ""
        },
        {
            "name": "MESSAGE",
            "baseName": "MESSAGE",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WatcherDict.attributeTypeMap;
    }

    public constructor() {
    }
}
