/**
 * RomM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.10.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WebrcadeFeedCategorySchema } from '../models/WebrcadeFeedCategorySchema';
import { HttpFile } from '../http/http';

export class WebrcadeFeedSchema {
    'title': string;
    'longTitle'?: string;
    'description'?: string;
    'thumbnail'?: string;
    'background'?: string;
    'categories': Array<WebrcadeFeedCategorySchema>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "longTitle",
            "baseName": "longTitle",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "thumbnail",
            "baseName": "thumbnail",
            "type": "string",
            "format": ""
        },
        {
            "name": "background",
            "baseName": "background",
            "type": "string",
            "format": ""
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<WebrcadeFeedCategorySchema>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebrcadeFeedSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
